{"uuid": "da46adb1-1cc3-4b73-991a-be0664946818", "children": ["2b43c7f1-34d3-4669-99dc-7ef34d682e91"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[text()=\"Войти в аккаунт\"]; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:507:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16\n\n", "trace": "  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\conftest.py\", line 53, in login\n    main_page.click_on_enter_account()\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\pages\\main_page.py\", line 10, in click_on_enter_account\n    self.move_to_element_and_click(MainPageLocators.ENTER_ACCOUNT)\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\pages\\base_page.py\", line 75, in move_to_element_and_click\n    element = self.driver.find_element(*locator)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 742, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Переходим на страницу логина кликом по кнопке \"Войти в аккаунт\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[text()=\"Войти в аккаунт\"]; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:507:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16\n\n", "trace": "  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\pages\\main_page.py\", line 10, in click_on_enter_account\n    self.move_to_element_and_click(MainPageLocators.ENTER_ACCOUNT)\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\pages\\base_page.py\", line 75, in move_to_element_and_click\n    element = self.driver.find_element(*locator)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 742, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Переместиться до элемента и кликнуть", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[text()=\"Войти в аккаунт\"]; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:507:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16\n\n", "trace": "  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\pages\\base_page.py\", line 75, in move_to_element_and_click\n    element = self.driver.find_element(*locator)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 742, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Hp\\PycharmProjects\\Diplom_3\\qa_python\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('xpath', '//button[text()=\"Войти в аккаунт\"]')"}], "start": 1705328930896, "stop": 1705328930905}], "start": 1705328930896, "stop": 1705328930906}], "start": 1705328930896, "stop": 1705328930906}], "start": 1705328930896, "stop": 1705328930955}